// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"src/internal/biz"
	"src/internal/conf"
	"src/internal/data"
	"src/internal/server"
	"src/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, boxOffice *conf.BoxOffice, auth *conf.Auth, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	movieRepo := data.NewMovieRepo(dataData, logger)
	boxOfficeClient := data.NewBoxOfficeClient(boxOffice, logger)
	movieUseCase := biz.NewMovieUseCase(movieRepo, boxOfficeClient, logger)
	ratingRepo := data.NewRatingRepo(dataData, logger)
	ratingUseCase := biz.NewRatingUseCase(movieRepo, ratingRepo, logger)
	movieService := service.NewMovieService(movieUseCase, ratingUseCase)
	grpcServer := server.NewGRPCServer(confServer, movieService, logger)
	httpServer := server.NewHTTPServer(confServer, movieService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
