server:
  http:
    addr: 0.0.0.0:8080
    timeout: 30s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 30s

data:
  database:
    driver: postgres
    source: ${DB_URL:postgres://app:app@db:5432/moviedb?sslmode=disable&timezone=UTC}
  redis:
    addr: ${REDIS_ADDR:redis:6379}
    read_timeout: 0.2s
    write_timeout: 0.2s

boxoffice:
  url: ${BOXOFFICE_URL:https://mock.apifox.com/m1/4288164-0-default}
  api_key: ${BOXOFFICE_API_KEY:your-api-key}
  timeout: 3s
  max_retries: 2

auth:
  token: ${AUTH_TOKEN:your-auth-token}
