server:
  http:
    addr: ${HTTP_ADDR}
    timeout: ${HTTP_TIMEOUT}
  grpc:
    addr: ${GRPC_ADDR}
    timeout: ${GRPC_TIMEOUT}

data:
  database:
    driver: postgres
    source: ${DB_URL}
  redis:
    addr: ${REDIS_ADDR}
    read_timeout: ${REDIS_READ_TIMEOUT}
    write_timeout: ${REDIS_WRITE_TIMEOUT}

boxoffice:
  url: ${BOXOFFICE_URL}
  api_key: ${BOXOFFICE_API_KEY}
  timeout: ${BOXOFFICE_TIMEOUT}
  max_retries: ${BOXOFFICE_MAX_RETRIES}

auth:
  token: ${AUTH_TOKEN}
